### ISSUE TITLE
DiscordAPIError: Unknown Member

### ISSUE THREAD

**Issue by Mysteriouslymythical** [detjensrobert/TwitchHoisterBot#7]
Hello!   I have tried reinstalling the bot and everything.  Whever I try to add a new user, the bot says 

"DiscordAPIError: Unknown Member" inside of console.   When I try again it says the user has been added, but they are not in the streamer list.  Here is the full error:

[ INFO ] Adding user korashu to streamer list
[ ERROR ] Uncaught Promise Rejection!
DiscordAPIError: Unknown Member
Uncaught Promise Rejection!
 DiscordAPIError: Unknown Member
    at RequestHandler.execute (/Users/******/Downloads/e/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/Users/*********/Downloads/e/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async Object.execute (/Users/*********/Downloads/e/commands/add.js:51:13) {
  method: 'get',
  path: '/guilds/846977623539449866/members/701140032223838338',
  code: 10007,
  httpStatus: 404
}

**Comment by detjensrobert** [comment]
Do you have intents enabled on your bot application?

![intents page](https://i.imgur.com/Gfvfu0b.png)

This bot uses the member list and presence data, and Discord gates that behind these switches. There's not really a good way to check and warn if these are not enabled unfortunately. :disappointed:

**Comment by Mysteriouslymythical** [comment]
Yes, I have them enabled

**Comment by detjensrobert** [comment]
I think I see what the problem is. I'll work on a fix shortly!

**Comment by detjensrobert** [comment]
@Mysteriouslymythical please try again with the latest master branch.

**Comment by Mysteriouslymythical** [comment]
Could I run this on repl.it?

**Comment by Mysteriouslymythical** [comment]
Also, is there a way to customize the code myself, so that instead of logging inside of console, it logs inside of a channel?

**Comment by detjensrobert** [comment]
> Could I run this on repl.it?

Probably not, I doubt that they will let you run a program for very long. Something like a spare Raspberry Pi or old computer you can leave on all the time would work much better,

> Also, is there a way to customize the code myself, so that instead of logging inside of console, it logs inside of a channel?

Yep, all logging is done through `utils/log.js`, so updating `log()` in there to send messages to a channel will do that.
